### PR TITLE
Fix wrong `\count($topic)` after `onClose`

### LINKED ISSUE #474: TopicPeriodicTimer doesn't see new connections
## Description
If the `Topic` temporarily has zero connections, the `TopicPeriodicTimer` doesn't see new connections, and it doesn't get re-registered either.

### Example code
```php
<?php

namespace App\Websocket\Topic;

use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimerInterface;
use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimerTrait;
use Ratchet\Wamp\Topic;

class AcmePeriodicTopic extends AcmeTopic implements TopicPeriodicTimerInterface
{
    use TopicPeriodicTimerTrait;

    public function registerPeriodicTimer(Topic $topic): void
    {
        // Adds the periodic timer the first time a client connects to the topic
        $this->periodicTimer->addPeriodicTimer(
            $this,
            'hello',
            300,
            function () use ($topic) {
                $topic->broadcast('Hello world');
            }
        );
    }

    /**
     * Name of the topic.
     */
    public function getName(): string
    {
        return 'acme.periodic.topic';
    }
}
```

### Steps
- client 1 subscribes to `acme.periodic.topic`
- timer is created, sees 1 connection
- client 1 disconnects/unsubscribes
- timer sees 0 connections, **stays alive**
- client 1 subscribes to `acme.periodic.topic`
- timer sees 0 connections 😕 

## Analysis
When there are zero connections, the `TopicManager` deletes the `Topic`, however the `TopicPeriodicTimer` is not deregistered and continues to hold a reference to the old `Topic` instance. When the `TopicManager` recreates the `Topic`, the `TopicPeriodicTimer` doesn't see any new connections.
Due to an ordering issue with `cleanTopic`, the `TopicDispatcher` never calls `TopicPeriodicTimer::clearPeriodicTimer`.

### Workaround:
```php
<?php

namespace App\Websocket\Topic;

use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimerInterface;
use Gos\Bundle\WebSocketBundle\Topic\TopicPeriodicTimerTrait;
use Ratchet\Wamp\Topic;

class AcmePeriodicTopic extends AcmeTopic implements TopicPeriodicTimerInterface
{
    use TopicPeriodicTimerTrait;

    public function registerPeriodicTimer(Topic $topic): void
    {
        // Adds the periodic timer the first time a client connects to the topic
        $this->periodicTimer->addPeriodicTimer(
            $this,
            'hello',
            300,
            function () use ($topic) {
                $topic->broadcast('Hello world');
            }
        );
    }

    /**
     * Handles unsubscription requests for this topic.
     */
    public function onUnSubscribe(ConnectionInterface $connection, Topic $topic, WampRequest $request): void
    {
        $topic->remove($connection);
    }

    /**
     * Name of the topic.
     */
    public function getName(): string
    {
        return 'acme.periodic.topic';
    }
}
```

### Steps
- client 1 subscribes to `acme.periodic.topic`
- timer is created, sees 1 connection
- client 1 disconnects/unsubscribes
- timer sees 0 connections, **gets canceled**
- client 1 subscribes to `acme.periodic.topic`
- timer is created, sees 1 connection 😄

### PR DESCRIPTION
**Pull request by Androbin**
Fixes #422
Fixes #474

### CODE REVIEW

**Comment by mbabker** [comment]
It looks like there's a test failure with `Gos\Bundle\WebSocketBundle\Tests\Server\App\Dispatcher\TopicDispatcherTest::testADispatchToAnUnregisteredPeriodicTopicTimerIsCompleted` and it needing an update for this PR.

There is already a call to clear the timer [here](https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/45e755a693b8d70e11df7f06d6f2dd3841687163/src/Server/App/Dispatcher/TopicDispatcher.php#L278-L280), after the `Gos\Bundle\WebSocketBundle\Topic\TopicInterface::onUnSubscribe()` method is called.  Is the added call to clear the topic before that method is called really needed?  That to me looks like it could have B/C impact as it changes the state of the event loop and the topic when the `onUnSubscribe()` method is called.

File: src/Topic/TopicManager.php [hunk 1]
```diff
@@ -76,11 +76,13 @@ public function onPublish(ConnectionInterface $conn, $topic, $event, array $excl
 
     public function onClose(ConnectionInterface $conn): void
     {
-        $this->app->onClose($conn);
-
         foreach ($this->topicLookup as $topic) {
             $this->cleanTopic($topic, $conn);
+
+            $this->app->onUnsubscribe($conn, $topic);
```
Comment (mbabker) [inline src/Topic/TopicManager.php:82]: I really wish I kept better notes from 2 years ago, but #422 added this same line and I ended up having to revert it after that PR made it to production for one of my clients.  I don't remember what happened exactly (and our Sentry logs are long purged from that rollout), or if that ended up being an incomplete fix for what you're working on here, but figured I'd point it out since it came to mind.

**Comment by Androbin** [comment]
The real issue is that `\count($topic)` gives the wrong value, due to an ordering issue. When `onUnsubscribe` is called directly, then `\count($topic) == 0`, but when it is called indirectly through `onClose`, then `\count($topic) == 1`.

Old behavior:
- `onUnsubscribe`: `cleanTopic`, `onUnsubscribe`
- `onClose`: `onUnsubscribe`, `onClose`, `cleanTopic`

New behavior:
- `onUnsubscribe`: `cleanTopic`, `onUnsubscribe`
- `onClose`: `cleanTopic`, `onUnsubscribe`, `onClose`

File: src/Topic/TopicManager.php (hunk 1 above)
Comment (Androbin) [reply src/Topic/TopicManager.php:82]: Ah, yes I think it's the same issue, let me take a look at what happened there.

Comment (Androbin) [reply src/Topic/TopicManager.php:82]: @mbabker I think the issue was that he didn't remove this, so `onUnsubscribe` got called twice:
https://github.com/GeniusesOfSymfony/WebSocketBundle/blob/3a8b6a0a78234f2f38fe2168ec2df423aa7d3950/src/Server/App/WampApplication.php#L175-L178

Comment (mbabker) [reply src/Topic/TopicManager.php:82]: Yeah, that would make sense.

Comment (Androbin) [reply src/Topic/TopicManager.php:82]: After his change, the order was: `onUnsubscribe`, `onClose`, `cleanTopic`, `onUnsubscribe`

Comment (Androbin) [reply src/Topic/TopicManager.php:82]: Since `cleanTopic` clears `$conn->WAMP->subscriptions`, it was necessary to move the call to `$this->topicDispatcher->onUnSubscribe` and to call it through `$this->app->onUnsubscribe($conn, $topic)` instead.
